import { createContext, useContext, useState } from 'react';

export const LANGUAGES = [
  { code: 'hi', name: 'हिंदी',       english: 'Hindi'     },
  { code: 'en', name: 'English',     english: 'English'   },
  { code: 'bn', name: 'বাংলা',       english: 'Bengali'   },
  { code: 'ta', name: 'தமிழ்',       english: 'Tamil'     },
  { code: 'te', name: 'తెలుగు',      english: 'Telugu'    },
  { code: 'mr', name: 'मराठी',       english: 'Marathi'   },
  { code: 'gu', name: 'ગુજરાતી',     english: 'Gujarati'  },
  { code: 'kn', name: 'ಕನ್ನಡ',       english: 'Kannada'   },
  { code: 'ml', name: 'മലയാളം',      english: 'Malayalam' },
  { code: 'pa', name: 'ਪੰਜਾਬੀ',      english: 'Punjabi'   },
  { code: 'or', name: 'ଓଡ଼ିଆ',       english: 'Odia'      },
  { code: 'as', name: 'অসমীয়া',     english: 'Assamese'  },
  { code: 'ur', name: 'اردو',        english: 'Urdu'      },
  { code: 'sa', name: 'संस्कृतम्',   english: 'Sanskrit'  },
  { code: 'ne', name: 'नेपाली',      english: 'Nepali'    },
  { code: 'sd', name: 'سنڌي',        english: 'Sindhi'    },
  { code: 'ks', name: 'كٲشُر',       english: 'Kashmiri'  },
  { code: 'mai',name: 'मैथिली',      english: 'Maithili'  },
  { code: 'kok',name: 'कोंकणी',      english: 'Konkani'   },
  { code: 'doi',name: 'डोगरी',       english: 'Dogri'     },
  { code: 'mni',name: 'মৈতৈলোন্',   english: 'Manipuri'  },
  { code: 'sat',name: 'ᱥᱟᱱᱛᱟᱲᱤ',   english: 'Santali'   },
  { code: 'brx',name: 'बड़ो',        english: 'Bodo'      },
];

// ── Full UI translations for every language ──────────────────────────
const T = {
  hi: {
    heroTitle1: 'नागरिक',
    heroTitle2: 'सहायक',
    heroDesc: 'कोई भी सरकारी दस्तावेज़ अपलोड करें और अपनी भाषा में तुरंत मार्गदर्शन पाएं — कोई बिचौलिया नहीं।',
    getStarted: 'शुरू करें →',
    changeLanguage: 'भाषा बदलें',
    whatNeed: 'आज आपको क्या चाहिए?',
    flow1Title: 'फॉर्म भरना है',
    flow1Sub: 'I have a form to fill',
    flow1Desc: 'फ़ील्ड-दर-फ़ील्ड मार्गदर्शन और तैयारी जाँच',
    flow2Title: 'आवेदन अस्वीकार हुआ',
    flow2Sub: 'I was rejected',
    flow2Desc: 'अस्वीकृति कारण समझें और ठीक करने की सूची पाएं',
    flow3Title: 'दस्तावेज़ जाँचें',
    flow3Sub: 'Check my documents',
    flow3Desc: 'जमा करने से पहले दस्तावेज़ सत्यापित करें',
    schemesLabel: 'समर्थित सरकारी योजनाएं',
    howWorks: 'यह कैसे काम करता है',
    recentActivity: 'हाल की गतिविधि',
    step1: 'अपलोड करें', step1d: 'कोई भी सरकारी दस्तावेज़',
    step2: 'AI विश्लेषण', step2d: 'OCR + 22 भाषाएं',
    step3: 'परिणाम पाएं', step3d: 'स्कोर + कार्य योजना',
    uploadTitle: 'दस्तावेज़ अपलोड करें',
    uploadDesc: 'खींचें और छोड़ें, या नीचे से चुनें',
    uploadTip: 'अच्छी रोशनी · सपाट सतह · सभी कोने दिखाई दें · JPEG, PNG या PDF · अधिकतम 10 MB',
    analyzeBtn: 'दस्तावेज़ विश्लेषण करें →',
    chooseLanguage: 'अपनी भाषा चुनें',
    searchLang: 'भाषा खोजें…',
    popularLangs: 'लोकप्रिय भाषाएं',
    allLangs: 'सभी {n} भाषाएं',
    showAll: 'सभी {n} भाषाएं दिखाएं ↓',
    poweredBy: 'Bhashini द्वारा संचालित · 22 भारतीय भाषाएं',
    back: 'वापस',
    overview: 'अवलोकन',
    actions: 'कार्य',
    details: 'विवरण',
    results: 'विश्लेषण परिणाम',
    home: 'होम',
    newScan: 'नया स्कैन',
    share: 'साझा करें',
    government: 'सरकारी AI सहायक',
    tagline: '"हर नागरिक का हक़, उनकी भाषा में"',
    taglineEn: 'Every citizen\'s right, in their own language',
  },
  en: {
    heroTitle1: 'Citizen',
    heroTitle2: 'Assistant',
    heroDesc: 'Upload any government document and get instant guidance in your language — no middlemen, no confusion.',
    getStarted: 'Get Started →',
    changeLanguage: 'Change Language',
    whatNeed: 'What do you need today?',
    flow1Title: 'I have a form to fill',
    flow1Sub: 'फॉर्म भरना है',
    flow1Desc: 'Field-by-field guidance and readiness check',
    flow2Title: 'I was rejected',
    flow2Sub: 'आवेदन अस्वीकार हुआ',
    flow2Desc: 'Understand rejection & get a fix-it checklist',
    flow3Title: 'Check my documents',
    flow3Sub: 'दस्तावेज़ जाँचें',
    flow3Desc: 'Validate documents before submission',
    schemesLabel: 'Supported Government Schemes',
    howWorks: 'How It Works',
    recentActivity: 'Recent Activity',
    step1: 'Upload', step1d: 'Any govt. document',
    step2: 'AI Analyzes', step2d: 'OCR + 22 languages',
    step3: 'Get Results', step3d: 'Score + action plan',
    uploadTitle: 'Upload Document',
    uploadDesc: 'Drag & drop, or choose below',
    uploadTip: 'Good lighting · flat surface · all corners visible · JPEG, PNG or PDF · max 10 MB',
    analyzeBtn: 'Analyze Document →',
    chooseLanguage: 'Choose Your Language',
    searchLang: 'Search language…',
    popularLangs: 'Popular Languages',
    allLangs: 'All {n} Languages',
    showAll: 'Show all {n} languages ↓',
    poweredBy: 'Powered by Bhashini · 22 Indian Languages',
    back: 'Back',
    overview: 'Overview',
    actions: 'Actions',
    details: 'Details',
    results: 'Analysis Results',
    home: 'Home',
    newScan: 'New Scan',
    share: 'Share',
    government: 'Government AI Assistant',
    tagline: '"हर नागरिक का हक़, उनकी भाषा में"',
    taglineEn: 'Every citizen\'s right, in their own language',
  },
  bn: {
    heroTitle1: 'নাগরিক',
    heroTitle2: 'সহায়ক',
    heroDesc: 'যেকোনো সরকারি নথি আপলোড করুন এবং আপনার ভাষায় তাৎক্ষণিক গাইডেন্স পান।',
    getStarted: 'শুরু করুন →',
    changeLanguage: 'ভাষা পরিবর্তন করুন',
    whatNeed: 'আজ আপনার কী দরকার?',
    flow1Title: 'ফর্ম পূরণ করতে হবে',
    flow1Sub: 'I have a form to fill',
    flow1Desc: 'ক্ষেত্র-অনুযায়ী গাইডেন্স এবং প্রস্তুতি যাচাই',
    flow2Title: 'আবেদন প্রত্যাখ্যাত হয়েছে',
    flow2Sub: 'I was rejected',
    flow2Desc: 'প্রত্যাখ্যানের কারণ বুঝুন এবং সমাধান পান',
    flow3Title: 'নথি যাচাই করুন',
    flow3Sub: 'Check my documents',
    flow3Desc: 'জমা দেওয়ার আগে নথি যাচাই করুন',
    schemesLabel: 'সমর্থিত সরকারি প্রকল্প',
    howWorks: 'এটি কীভাবে কাজ করে',
    recentActivity: 'সাম্প্রতিক কার্যক্রম',
    step1: 'আপলোড', step1d: 'যেকোনো সরকারি নথি',
    step2: 'AI বিশ্লেষণ', step2d: 'OCR + ২২ ভাষা',
    step3: 'ফলাফল পান', step3d: 'স্কোর + কর্ম পরিকল্পনা',
    uploadTitle: 'নথি আপলোড করুন',
    uploadDesc: 'টেনে আনুন বা নীচ থেকে বেছে নিন',
    uploadTip: 'ভালো আলো · সমতল পৃষ্ঠ · সব কোণ দৃশ্যমান · JPEG, PNG বা PDF · সর্বোচ্চ ১০ MB',
    analyzeBtn: 'নথি বিশ্লেষণ করুন →',
    chooseLanguage: 'আপনার ভাষা বেছে নিন',
    searchLang: 'ভাষা খুঁজুন…',
    popularLangs: 'জনপ্রিয় ভাষাসমূহ',
    allLangs: 'সকল {n} ভাষা',
    showAll: 'সকল {n} ভাষা দেখান ↓',
    poweredBy: 'Bhashini দ্বারা চালিত · ২২টি ভারতীয় ভাষা',
    back: 'ফিরে যান',
    overview: 'সারসংক্ষেপ',
    actions: 'কার্যক্রম',
    details: 'বিবরণ',
    results: 'বিশ্লেষণ ফলাফল',
    home: 'হোম',
    newScan: 'নতুন স্ক্যান',
    share: 'শেয়ার করুন',
    government: 'সরকারি AI সহায়ক',
    tagline: '"হর নাগরিক কা হক, উনকি ভাষা মে"',
    taglineEn: 'Every citizen\'s right, in their own language',
  },
  ta: {
    heroTitle1: 'குடிமக்கள்',
    heroTitle2: 'உதவியாளர்',
    heroDesc: 'எந்த அரசு ஆவணத்தையும் பதிவேற்றி உங்கள் மொழியில் உடனடி வழிகாட்டுதல் பெறுங்கள்.',
    getStarted: 'தொடங்குங்கள் →',
    changeLanguage: 'மொழி மாற்றவும்',
    whatNeed: 'இன்று உங்களுக்கு என்ன தேவை?',
    flow1Title: 'படிவம் நிரப்ப வேண்டும்',
    flow1Sub: 'I have a form to fill',
    flow1Desc: 'புலம்-வாரியாக வழிகாட்டுதல் மற்றும் தயார்நிலை சரிபார்ப்பு',
    flow2Title: 'விண்ணப்பம் நிராகரிக்கப்பட்டது',
    flow2Sub: 'I was rejected',
    flow2Desc: 'நிராகரிப்பு காரணங்களை புரிந்துகொண்டு தீர்வு பெறுங்கள்',
    flow3Title: 'ஆவணங்களை சரிபார்க்கவும்',
    flow3Sub: 'Check my documents',
    flow3Desc: 'சமர்ப்பிக்கும் முன் ஆவணங்களை சரிபார்க்கவும்',
    schemesLabel: 'ஆதரிக்கப்படும் அரசு திட்டங்கள்',
    howWorks: 'இது எப்படி செயல்படுகிறது',
    recentActivity: 'சமீபத்திய செயல்பாடு',
    step1: 'பதிவேற்று', step1d: 'எந்த அரசு ஆவணமும்',
    step2: 'AI பகுப்பாய்வு', step2d: 'OCR + 22 மொழிகள்',
    step3: 'முடிவுகள் பெறவும்', step3d: 'மதிப்பெண் + செயல் திட்டம்',
    uploadTitle: 'ஆவணத்தை பதிவேற்றவும்',
    uploadDesc: 'இழுத்து விடுங்கள் அல்லது கீழே தேர்வு செய்யுங்கள்',
    uploadTip: 'நல்ல வெளிச்சம் · தட்டையான மேற்பரப்பு · அனைத்து மூலைகளும் தெரியும் · JPEG, PNG அல்லது PDF · அதிகபட்சம் 10 MB',
    analyzeBtn: 'ஆவணத்தை பகுப்பாய்வு செய்யவும் →',
    chooseLanguage: 'உங்கள் மொழியை தேர்ந்தெடுங்கள்',
    searchLang: 'மொழி தேடுங்கள்…',
    popularLangs: 'பிரபலமான மொழிகள்',
    allLangs: 'அனைத்து {n} மொழிகள்',
    showAll: 'அனைத்து {n} மொழிகளையும் காட்டு ↓',
    poweredBy: 'Bhashini ஆல் இயக்கப்படுகிறது · 22 இந்திய மொழிகள்',
    back: 'திரும்பு',
    overview: 'கண்ணோட்டம்',
    actions: 'நடவடிக்கைகள்',
    details: 'விவரங்கள்',
    results: 'பகுப்பாய்வு முடிவுகள்',
    home: 'முகப்பு',
    newScan: 'புதிய ஸ்கேன்',
    share: 'பகிர்வு',
    government: 'அரசு AI உதவியாளர்',
    tagline: '"ஒவ்வொரு குடிமகனின் உரிமை, அவரவர் மொழியில்"',
    taglineEn: 'Every citizen\'s right, in their own language',
  },
  te: {
    heroTitle1: 'పౌర',
    heroTitle2: 'సహాయకుడు',
    heroDesc: 'ఏదైనా ప్రభుత్వ పత్రాన్ని అప్‌లోడ్ చేసి మీ భాషలో తక్షణ మార్గదర్శకత్వం పొందండి.',
    getStarted: 'ప్రారంభించండి →',
    changeLanguage: 'భాష మార్చండి',
    whatNeed: 'ఈరోజు మీకు ఏమి కావాలి?',
    flow1Title: 'ఫారం నింపాలి',
    flow1Sub: 'I have a form to fill',
    flow1Desc: 'ఫీల్డ్-వారీ మార్గదర్శకత్వం మరియు సంసిద్ధత తనిఖీ',
    flow2Title: 'దరఖాస్తు తిరస్కరించబడింది',
    flow2Sub: 'I was rejected',
    flow2Desc: 'తిరస్కరణ కారణాలను అర్థం చేసుకుని పరిష్కారం పొందండి',
    flow3Title: 'పత్రాలు తనిఖీ చేయండి',
    flow3Sub: 'Check my documents',
    flow3Desc: 'సమర్పించే ముందు పత్రాలు ధృవీకరించండి',
    schemesLabel: 'మద్దతు ఉన్న ప్రభుత్వ పథకాలు',
    howWorks: 'ఇది ఎలా పని చేస్తుంది',
    recentActivity: 'ఇటీవలి కార్యకలాపం',
    step1: 'అప్‌లోడ్', step1d: 'ఏదైనా ప్రభుత్వ పత్రం',
    step2: 'AI విశ్లేషణ', step2d: 'OCR + 22 భాషలు',
    step3: 'ఫలితాలు పొందండి', step3d: 'స్కోరు + చర్య ప్రణాళిక',
    uploadTitle: 'పత్రం అప్‌లోడ్ చేయండి',
    uploadDesc: 'లాగండి & వదలండి, లేదా దిగువ నుండి ఎంచుకోండి',
    uploadTip: 'మంచి వెలుతురు · చదునైన ఉపరితలం · అన్ని మూలలు కనిపించాలి · JPEG, PNG లేదా PDF · గరిష్టంగా 10 MB',
    analyzeBtn: 'పత్రాన్ని విశ్లేషించండి →',
    chooseLanguage: 'మీ భాష ఎంచుకోండి',
    searchLang: 'భాష వెతకండి…',
    popularLangs: 'ప్రముఖ భాషలు',
    allLangs: 'అన్ని {n} భాషలు',
    showAll: 'అన్ని {n} భాషలు చూపించు ↓',
    poweredBy: 'Bhashini ద్వారా నడపబడుతోంది · 22 భారతీయ భాషలు',
    back: 'వెనుకకు',
    overview: 'అవలోకనం',
    actions: 'చర్యలు',
    details: 'వివరాలు',
    results: 'విశ్లేషణ ఫలితాలు',
    home: 'హోమ్',
    newScan: 'కొత్త స్కాన్',
    share: 'షేర్',
    government: 'ప్రభుత్వ AI సహాయకుడు',
    tagline: '"ప్రతి పౌరుని హక్కు, వారి భాషలో"',
    taglineEn: 'Every citizen\'s right, in their own language',
  },
  mr: {
    heroTitle1: 'नागरिक',
    heroTitle2: 'सहाय्यक',
    heroDesc: 'कोणताही सरकारी दस्तऐवज अपलोड करा आणि आपल्या भाषेत तत्काळ मार्गदर्शन मिळवा.',
    getStarted: 'सुरू करा →',
    changeLanguage: 'भाषा बदला',
    whatNeed: 'आज तुम्हाला काय हवे आहे?',
    flow1Title: 'फॉर्म भरायचा आहे',
    flow1Sub: 'I have a form to fill',
    flow1Desc: 'फील्ड-बाय-फील्ड मार्गदर्शन आणि तयारी तपासणी',
    flow2Title: 'अर्ज नाकारला गेला',
    flow2Sub: 'I was rejected',
    flow2Desc: 'नकाराचे कारण समजून घ्या आणि उपाय मिळवा',
    flow3Title: 'कागदपत्रे तपासा',
    flow3Sub: 'Check my documents',
    flow3Desc: 'सादर करण्यापूर्वी कागदपत्रे सत्यापित करा',
    schemesLabel: 'समर्थित सरकारी योजना',
    howWorks: 'हे कसे कार्य करते',
    recentActivity: 'अलीकडील क्रियाकलाप',
    step1: 'अपलोड करा', step1d: 'कोणतेही सरकारी दस्तऐवज',
    step2: 'AI विश्लेषण', step2d: 'OCR + 22 भाषा',
    step3: 'निकाल मिळवा', step3d: 'स्कोअर + कृती योजना',
    uploadTitle: 'दस्तऐवज अपलोड करा',
    uploadDesc: 'ड्रॅग करा व सोडा, किंवा खाली निवडा',
    uploadTip: 'चांगला प्रकाश · सपाट पृष्ठभाग · सर्व कोपरे दिसत असावेत · JPEG, PNG किंवा PDF · जास्तीत जास्त 10 MB',
    analyzeBtn: 'दस्तऐवज विश्लेषण करा →',
    chooseLanguage: 'तुमची भाषा निवडा',
    searchLang: 'भाषा शोधा…',
    popularLangs: 'लोकप्रिय भाषा',
    allLangs: 'सर्व {n} भाषा',
    showAll: 'सर्व {n} भाषा दाखवा ↓',
    poweredBy: 'Bhashini द्वारे चालवले · 22 भारतीय भाषा',
    back: 'मागे',
    overview: 'आढावा',
    actions: 'कृती',
    details: 'तपशील',
    results: 'विश्लेषण निकाल',
    home: 'होम',
    newScan: 'नवीन स्कॅन',
    share: 'शेअर करा',
    government: 'सरकारी AI सहाय्यक',
    tagline: '"प्रत्येक नागरिकाचा हक्क, त्यांच्या भाषेत"',
    taglineEn: 'Every citizen\'s right, in their own language',
  },
  gu: {
    heroTitle1: 'નાગરિક',
    heroTitle2: 'સહાયક',
    heroDesc: 'કોઈ પણ સરકારી દસ્તાવેજ અપલોડ કરો અને તમારી ભાષામાં તાત્કાલિક માર્ગદર્શન મેળવો.',
    getStarted: 'શરૂ કરો →',
    changeLanguage: 'ભાષા બદલો',
    whatNeed: 'આજે તમારે શું જોઈએ છે?',
    flow1Title: 'ફોર્મ ભરવાનો છે',
    flow1Sub: 'I have a form to fill',
    flow1Desc: 'ફીલ્ડ-દ્વારા-ફીલ્ડ માર્ગદર્શન અને તૈયારી ચકાસણી',
    flow2Title: 'અરજી નામંજૂર થઈ',
    flow2Sub: 'I was rejected',
    flow2Desc: 'નકારના કારણો સમજો અને ઉકેલ મેળવો',
    flow3Title: 'દસ્તાવેજો ચકાસો',
    flow3Sub: 'Check my documents',
    flow3Desc: 'સુપ્રત કરતા પહેલા દસ્તાવેજો ચકાસો',
    schemesLabel: 'સમર્થિત સરકારી યોજनाઓ',
    howWorks: 'આ કેવી રીતે કામ કરે છે',
    recentActivity: 'તાજેતરની પ્રવૃત્તિ',
    step1: 'અપલોડ', step1d: 'કોઈ પણ સ.દ.',
    step2: 'AI વિશ્લેષણ', step2d: 'OCR + 22 ભાષા',
    step3: 'પરિણામ મળો', step3d: 'સ્કોર + યોજना',
    uploadTitle: 'દસ્તાવેજ અપલોડ કરો',
    uploadDesc: 'ખેંચો અને છોડો, અથવા નીચેથી પસંદ કરો',
    uploadTip: 'સારો પ્રકાશ · સ્ tat पृष्ठभूमि · JPEG, PNG અથવા PDF · મહત્તમ 10 MB',
    analyzeBtn: 'દસ્તાવેજ વિશ્લેષણ કરો →',
    chooseLanguage: 'તમારી ભાષા પસંદ કરો',
    searchLang: 'ભાષા શોધો…',
    popularLangs: 'લોકприй ભाषা',
    allLangs: 'બધી {n} ભाषाઓ',
    showAll: 'બધી {n} ભाषाઓ બতावо ↓',
    poweredBy: 'Bhashini દ્વारा चालित · 22 भारतीय ભाषाઓ',
    back: 'પаછа',
    overview: 'ઝаτкий',
    actions: 'ক্রিয়া',
    details: 'виваран',
    results: 'বিश्लेষণ ফলাফল',
    home: 'होम',
    newScan: 'নতুন স্ক্যান',
    share: 'শেয়ার',
    government: 'સरকारी AI सहায়ক',
    tagline: '"दरेक नागरिकनो हक, तेमनी भाषामां"',
    taglineEn: 'Every citizen\'s right, in their own language',
  },
  kn: {
    heroTitle1: 'ನಾಗರಿಕ',
    heroTitle2: 'ಸಹಾಯಕ',
    heroDesc: 'ಯಾವುದೇ ಸರ್ಕಾರಿ ದಾಖಲೆ ಅಪ್‌ಲೋಡ್ ಮಾಡಿ ಮತ್ತು ನಿಮ್ಮ ಭಾಷೆಯಲ್ಲಿ ತಕ್ಷಣದ ಮಾರ್ಗದರ್ಶನ ಪಡೆಯಿರಿ.',
    getStarted: 'ಪ್ರಾರಂಭಿಸಿ →',
    changeLanguage: 'ಭಾಷೆ ಬದಲಿಸಿ',
    whatNeed: 'ಇಂದು ನಿಮಗೆ ಏನು ಬೇಕು?',
    flow1Title: 'ಫಾರ್ಮ್ ತುಂಬಬೇಕು',
    flow1Sub: 'I have a form to fill',
    flow1Desc: 'ಕ್ಷೇತ್ರ-ಮೂಲಕ-ಕ್ಷೇತ್ರ ಮಾರ್ಗದರ್ಶನ ಮತ್ತು ಸಿದ್ಧತೆ ಪರಿಶೀಲನೆ',
    flow2Title: 'ಅರ್ಜಿ ತಿರಸ್ಕರಿಸಲಾಗಿದೆ',
    flow2Sub: 'I was rejected',
    flow2Desc: 'ತಿರಸ್ಕಾರದ ಕಾರಣಗಳನ್ನು ಅರ್ಥಮಾಡಿಕೊಳ್ಳಿ ಮತ್ತು ಪರಿಹಾರ ಪಡೆಯಿರಿ',
    flow3Title: 'ದಾಖಲೆಗಳನ್ನು ಪರಿಶೀಲಿಸಿ',
    flow3Sub: 'Check my documents',
    flow3Desc: 'ಸಲ್ಲಿಸುವ ಮೊದಲು ದಾಖಲೆಗಳನ್ನು ಮೌಲ್ಯಮಾಪನ ಮಾಡಿ',
    schemesLabel: 'ಬೆಂಬಲಿತ ಸರ್ಕಾರಿ ಯೋಜನೆಗಳು',
    howWorks: 'ಇದು ಹೇಗೆ ಕಾರ್ಯನಿರ್ವಹಿಸುತ್ತದೆ',
    recentActivity: 'ಇತ್ತೀಚಿನ ಚಟುವಟಿಕೆ',
    step1: 'ಅಪ್‌ಲೋಡ್', step1d: 'ಯಾವುದೇ ಸರ್ಕಾರಿ ದಾಖಲೆ',
    step2: 'AI ವಿಶ್ಲೇಷಣೆ', step2d: 'OCR + 22 ಭಾಷೆಗಳು',
    step3: 'ಫಲಿತಾಂಶ ಪಡೆಯಿರಿ', step3d: 'ಸ್ಕೋರ್ + ಕ್ರಿಯಾ ಯೋಜನೆ',
    uploadTitle: 'ದಾಖಲೆ ಅಪ್‌ಲೋಡ್ ಮಾಡಿ',
    uploadDesc: 'ಎಳೆದು ಬಿಡಿ, ಅಥವಾ ಕೆಳಗಿನಿಂದ ಆಯ್ಕೆ ಮಾಡಿ',
    uploadTip: 'ಒಳ್ಳೆಯ ಬೆಳಕು · ಸಮತಟ್ಟಾದ ಮೇಲ್ಮೈ · JPEG, PNG ಅಥವಾ PDF · ಗರಿಷ್ಠ 10 MB',
    analyzeBtn: 'ದಾಖಲೆ ವಿಶ್ಲೇಷಿಸಿ →',
    chooseLanguage: 'ನಿಮ್ಮ ಭಾಷೆ ಆಯ್ಕೆ ಮಾಡಿ',
    searchLang: 'ಭಾಷೆ ಹುಡುಕಿ…',
    popularLangs: 'ಜನಪ್ರಿಯ ಭಾಷೆಗಳು',
    allLangs: 'ಎಲ್ಲಾ {n} ಭಾಷೆಗಳು',
    showAll: 'ಎಲ್ಲಾ {n} ಭಾಷೆಗಳನ್ನು ತೋರಿಸು ↓',
    poweredBy: 'Bhashini ಮೂಲಕ ನಡೆಸಲಾಗುತ್ತದೆ · 22 ಭಾರತೀಯ ಭಾಷೆಗಳು',
    back: 'ಹಿಂದೆ',
    overview: 'ಅವಲೋಕನ',
    actions: 'ಕ್ರಿಯೆಗಳು',
    details: 'ವಿವರಗಳು',
    results: 'ವಿಶ್ಲೇಷಣೆ ಫಲಿತಾಂಶಗಳು',
    home: 'ಮುಖಪುಟ',
    newScan: 'ಹೊಸ ಸ್ಕ್ಯಾನ್',
    share: 'ಹಂಚಿಕೊಳ್ಳಿ',
    government: 'ಸರ್ಕಾರಿ AI ಸಹಾಯಕ',
    tagline: '"ಪ್ರತಿ ನಾಗರಿಕನ ಹಕ್ಕು, ಅವರ ಭಾಷೆಯಲ್ಲಿ"',
    taglineEn: 'Every citizen\'s right, in their own language',
  },
  ml: {
    heroTitle1: 'പൗര',
    heroTitle2: 'സഹായി',
    heroDesc: 'ഏത് സർക്കാർ രേഖയും അപ്‌ലോഡ് ചെയ്ത് നിങ്ങളുടെ ഭാഷയിൽ ഉടനടി മാർഗ്ഗനിർദ്ദേശം നേടൂ.',
    getStarted: 'ആരംഭിക്കൂ →',
    changeLanguage: 'ഭാഷ മാറ്റുക',
    whatNeed: 'ഇന്ന് നിങ്ങൾക്ക് എന്ത് വേണം?',
    flow1Title: 'ഫോം പൂരിപ്പിക്കണം',
    flow1Sub: 'I have a form to fill',
    flow1Desc: 'ഫീൽഡ്-അനുസരിച്ച് മാർഗ്ഗനിർദ്ദേശവും തയ്യാറെടുപ്പ് പരിശോധനയും',
    flow2Title: 'അപേക്ഷ നിരസിച്ചു',
    flow2Sub: 'I was rejected',
    flow2Desc: 'നിരാകരണ കാരണങ്ങൾ മനസ്സിലാക്കി പരിഹാരം കണ്ടെത്തൂ',
    flow3Title: 'രേഖകൾ പരിശോധിക്കൂ',
    flow3Sub: 'Check my documents',
    flow3Desc: 'സമർപ്പിക്കുന്നതിന് മുമ്പ് രേഖകൾ സ്ഥിരീകരിക്കൂ',
    schemesLabel: 'പിന്തുണ ലഭിക്കുന്ന സർക്കാർ പദ്ധതികൾ',
    howWorks: 'ഇത് എങ്ങനെ പ്രവർത്തിക്കുന്നു',
    recentActivity: 'സമീപകാല പ്രവർത്തനം',
    step1: 'അപ്‌ലോഡ്', step1d: 'ഏത് സർ. രേഖയും',
    step2: 'AI വിശകലനം', step2d: 'OCR + 22 ഭാഷകൾ',
    step3: 'ഫലം നേടൂ', step3d: 'സ്‌കോർ + പദ്ധതി',
    uploadTitle: 'രേഖ അപ്‌ലോഡ് ചെയ്യൂ',
    uploadDesc: 'വലിച്ചിടൂ അല്ലെങ്കിൽ താഴെ നിന്ന് തിരഞ്ഞെടുക്കൂ',
    uploadTip: 'നല്ല വെളിച്ചം · പരന്ന ഉപരിതലം · JPEG, PNG അല്ലെങ്കിൽ PDF · പരമാവധി 10 MB',
    analyzeBtn: 'രേഖ വിശകലനം ചെയ്യൂ →',
    chooseLanguage: 'നിങ്ങളുടെ ഭാഷ തിരഞ്ഞെടുക്കൂ',
    searchLang: 'ഭാഷ തിരയൂ…',
    popularLangs: 'ജനപ്രിയ ഭാഷകൾ',
    allLangs: 'എല്ലാ {n} ഭാഷകളും',
    showAll: 'എല്ലാ {n} ഭാഷകളും കാണൂ ↓',
    poweredBy: 'Bhashini വഴി പ്രവർത്തിക്കുന്നു · 22 ഇന്ത്യൻ ഭാഷകൾ',
    back: 'തിരിച്ചു',
    overview: 'അവലോകനം',
    actions: 'നടപടികൾ',
    details: 'വിശദാംശങ്ങൾ',
    results: 'വിശകലന ഫലങ്ങൾ',
    home: 'ഹോം',
    newScan: 'പുതിയ സ്‌കാൻ',
    share: 'പങ്കിടൂ',
    government: 'സർക്കാർ AI സഹായി',
    tagline: '"ഓരോ പൗരന്റെ അവകാശം, അവരുടെ ഭാഷയിൽ"',
    taglineEn: 'Every citizen\'s right, in their own language',
  },
  pa: {
    heroTitle1: 'ਨਾਗਰਿਕ',
    heroTitle2: 'ਸਹਾਇਕ',
    heroDesc: 'ਕੋਈ ਵੀ ਸਰਕਾਰੀ ਦਸਤਾਵੇਜ਼ ਅਪਲੋਡ ਕਰੋ ਅਤੇ ਆਪਣੀ ਭਾਸ਼ਾ ਵਿੱਚ ਤੁਰੰਤ ਮਾਰਗਦਰਸ਼ਨ ਪ੍ਰਾਪਤ ਕਰੋ।',
    getStarted: 'ਸ਼ੁਰੂ ਕਰੋ →',
    changeLanguage: 'ਭਾਸ਼ਾ ਬਦਲੋ',
    whatNeed: 'ਅੱਜ ਤੁਹਾਨੂੰ ਕੀ ਚਾਹੀਦਾ ਹੈ?',
    flow1Title: 'ਫਾਰਮ ਭਰਨਾ ਹੈ',
    flow1Sub: 'I have a form to fill',
    flow1Desc: 'ਫੀਲਡ-ਦਰ-ਫੀਲਡ ਮਾਰਗਦਰਸ਼ਨ ਅਤੇ ਤਿਆਰੀ ਜਾਂਚ',
    flow2Title: 'ਅਰਜ਼ੀ ਰੱਦ ਹੋ ਗਈ',
    flow2Sub: 'I was rejected',
    flow2Desc: 'ਰੱਦ ਹੋਣ ਦੇ ਕਾਰਨ ਸਮਝੋ ਅਤੇ ਹੱਲ ਲਓ',
    flow3Title: 'ਦਸਤਾਵੇਜ਼ ਜਾਂਚੋ',
    flow3Sub: 'Check my documents',
    flow3Desc: 'ਜਮ੍ਹਾ ਕਰਨ ਤੋਂ ਪਹਿਲਾਂ ਦਸਤਾਵੇਜ਼ ਪ੍ਰਮਾਣਿਤ ਕਰੋ',
    schemesLabel: 'ਸਮਰਥਿਤ ਸਰਕਾਰੀ ਯੋਜਨਾਵਾਂ',
    howWorks: 'ਇਹ ਕਿਵੇਂ ਕੰਮ ਕਰਦਾ ਹੈ',
    recentActivity: 'ਹਾਲੀਆ ਗਤੀਵਿਧੀ',
    step1: 'ਅਪਲੋਡ', step1d: 'ਕੋਈ ਵੀ ਸਰ. ਦਸਤਾਵੇਜ਼',
    step2: 'AI ਵਿਸ਼ਲੇਸ਼ਣ', step2d: 'OCR + 22 ਭਾਸ਼ਾਵਾਂ',
    step3: 'ਨਤੀਜੇ ਪਾਓ', step3d: 'ਸਕੋਰ + ਕਾਰਜ ਯੋਜਨਾ',
    uploadTitle: 'ਦਸਤਾਵੇਜ਼ ਅਪਲੋਡ ਕਰੋ',
    uploadDesc: 'ਖਿੱਚੋ ਅਤੇ ਛੱਡੋ, ਜਾਂ ਹੇਠਾਂ ਤੋਂ ਚੁਣੋ',
    uploadTip: 'ਚੰਗੀ ਰੌਸ਼ਨੀ · ਸਮਤਲ ਸਤਹ · JPEG, PNG ਜਾਂ PDF · ਵੱਧ ਤੋਂ ਵੱਧ 10 MB',
    analyzeBtn: 'ਦਸਤਾਵੇਜ਼ ਵਿਸ਼ਲੇਸ਼ਣ ਕਰੋ →',
    chooseLanguage: 'ਆਪਣੀ ਭਾਸ਼ਾ ਚੁਣੋ',
    searchLang: 'ਭਾਸ਼ਾ ਖੋਜੋ…',
    popularLangs: 'ਪ੍ਰਸਿੱਧ ਭਾਸ਼ਾਵਾਂ',
    allLangs: 'ਸਾਰੀਆਂ {n} ਭਾਸ਼ਾਵਾਂ',
    showAll: 'ਸਾਰੀਆਂ {n} ਭਾਸ਼ਾਵਾਂ ਦਿਖਾਓ ↓',
    poweredBy: 'Bhashini ਦੁਆਰਾ ਚਲਾਇਆ · 22 ਭਾਰਤੀ ਭਾਸ਼ਾਵਾਂ',
    back: 'ਵਾਪਸ',
    overview: 'ਸੰਖੇਪ',
    actions: 'ਕਾਰਵਾਈਆਂ',
    details: 'ਵੇਰਵੇ',
    results: 'ਵਿਸ਼ਲੇਸ਼ਣ ਨਤੀਜੇ',
    home: 'ਹੋਮ',
    newScan: 'ਨਵਾਂ ਸਕੈਨ',
    share: 'ਸਾਂਝਾ ਕਰੋ',
    government: 'ਸਰਕਾਰੀ AI ਸਹਾਇਕ',
    tagline: '"ਹਰ ਨਾਗਰਿਕ ਦਾ ਹੱਕ, ਉਨ੍ਹਾਂ ਦੀ ਭਾਸ਼ਾ ਵਿੱਚ"',
    taglineEn: 'Every citizen\'s right, in their own language',
  },
};

// Remaining languages fall back to English UI with native script for titles only
const NATIVE_TITLES = {
  or:  { t1: 'ନାଗରିକ',    t2: 'ସହାୟକ'     },
  as:  { t1: 'নাগৰিক',    t2: 'সহায়ক'     },
  ur:  { t1: 'شہری',       t2: 'معاون'      },
  sa:  { t1: 'नागरिक',    t2: 'सहायकः'     },
  ne:  { t1: 'नागरिक',    t2: 'सहायक'      },
  sd:  { t1: 'شهري',       t2: 'مددگار'     },
  ks:  { t1: 'شہری',       t2: 'مدددار'     },
  mai: { t1: 'नागरिक',    t2: 'सहायक'      },
  kok: { t1: 'नागरिक',    t2: 'सहायक'      },
  doi: { t1: 'नागरिक',    t2: 'सहायक'      },
  mni: { t1: 'নাগরিক',    t2: 'লাইরিক্স'  },
  sat: { t1: 'ᱱᱟᱜᱟᱨᱤᱠ', t2: 'ᱡᱳᱦᱳᱨ'    },
  brx: { t1: 'नागरिक',    t2: 'सहाय'       },
};

const LanguageContext = createContext({});

export const LanguageProvider = ({ children }) => {
  const [langCode, setLangCode] = useState(
    () => localStorage.getItem('cais_language') || ''
  );

  const setLanguage = (code) => {
    setLangCode(code);
    localStorage.setItem('cais_language', code);
  };

  // t() — returns translated string; falls back to en
  const t = (key) => {
    const dict = T[langCode];
    if (dict && dict[key] !== undefined) return dict[key];
    return T['en'][key] || key;
  };

  // For remaining langs, heroTitle uses native script
  const heroTitle1 = () => {
    if (T[langCode]) return T[langCode].heroTitle1;
    return NATIVE_TITLES[langCode]?.t1 || T['en'].heroTitle1;
  };
  const heroTitle2 = () => {
    if (T[langCode]) return T[langCode].heroTitle2;
    return NATIVE_TITLES[langCode]?.t2 || T['en'].heroTitle2;
  };

  const lang = LANGUAGES.find((l) => l.code === langCode) || null;

  return (
    <LanguageContext.Provider value={{ langCode, lang, setLanguage, languages: LANGUAGES, t, heroTitle1, heroTitle2 }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => useContext(LanguageContext);
